/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type CustomerIdUasgelimitBody struct {
	Amount int32 `json:"amount"`
	Action string `json:"action"`
}
