/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type Feature struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	Code string `json:"code,omitempty"`
	Description string `json:"description,omitempty"`
}
