/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type PaymentDetails struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Default_ bool `json:"default,omitempty"`
	Brand string `json:"brand,omitempty"`
	LastFour string `json:"last_four,omitempty"`
	ExpiryMonth string `json:"expiry_month,omitempty"`
	ExpiryYear string `json:"expiry_year,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
