/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20010 struct {
	Data []Product `json:"data,omitempty"`
	HasMore bool `json:"has_more,omitempty"`
	LastKey string `json:"last_key,omitempty"`
}
