/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type BillingAdmin struct {
	Id string `json:"id,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
}
