/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutBody struct {
	Name string `json:"name,omitempty"`
	Brand string `json:"brand"`
	Slug string `json:"slug,omitempty"`
	Customer string `json:"customer"`
	Items []CheckoutItems `json:"items,omitempty"`
	Subscriptions []CheckoutSubscriptions `json:"subscriptions,omitempty"`
}
