/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type InlineResponse201 struct {
	Id *Uuid `json:"id"`
	Name string `json:"name,omitempty"`
	Currency string `json:"currency,omitempty"`
	Customer *Customer `json:"customer,omitempty"`
	BillingAdmin *BillingAdmin `json:"billing_admin,omitempty"`
	Total int32 `json:"total,omitempty"`
	SubTotal int32 `json:"sub_total,omitempty"`
	TaxTotal int32 `json:"tax_total,omitempty"`
	Lines []InlineResponse201Lines `json:"lines,omitempty"`
}
