/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type SubscriptionPlan struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	CodeName string `json:"code_name,omitempty"`
	UserCount int32 `json:"user_count,omitempty"`
	PerSeat bool `json:"per_seat,omitempty"`
	HasTrial bool `json:"has_trial,omitempty"`
	IsTrialStandalone bool `json:"is_trial_standalone,omitempty"`
	Free bool `json:"free,omitempty"`
	Public bool `json:"public,omitempty"`
	Limits []Limit `json:"limits,omitempty"`
	Features []Feature `json:"features,omitempty"`
	Product *Product `json:"product,omitempty"`
	Prices []Price `json:"prices,omitempty"`
	TrialLengthDays int32 `json:"trial_length_days,omitempty"`
}
