/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Customer struct {
	Id string `json:"id,omitempty"`
	Email string `json:"email"`
	// The tax number for the customer <strong>Since 1.1</strong>
	TaxNumber string `json:"tax_number,omitempty"`
	// The tax rate for the customer on for standard services a <strong>Since 1.1</strong>
	StandardTaxRate float32 `json:"standard_tax_rate,omitempty"`
	// The tax rate for the customer on digital services <strong>Since 1.1</strong>
	DigitalTaxRate float32 `json:"digital_tax_rate,omitempty"`
	// Choice between card and invoice
	BillingType string `json:"billing_type,omitempty"`
	// Choice between 'individual' and 'business'. When not provided 'individual' is used. <strong>Since 1.1</strong>
	Type_ string `json:"type,omitempty"`
	Reference string `json:"reference,omitempty"`
	ExternalReference string `json:"external_reference,omitempty"`
	Address *Address `json:"address,omitempty"`
	// Defaults to 'en' if not sent.
	Locale string `json:"locale,omitempty"`
	// Defaults to 'default' if not sent.
	Brand string `json:"brand,omitempty"`
}
