/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductTaxType struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	Default_ bool `json:"default,omitempty"`
}
