/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Product struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	// The reference given by the payment provider
	ExternalReference string `json:"external_reference,omitempty"`
	TaxType *ProductTaxType `json:"tax_type,omitempty"`
}
