/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2009Receipts struct {
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	Valid bool `json:"valid,omitempty"`
}
