/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionIdCancelBody struct {
	When string `json:"when"`
	RefundType string `json:"refund_type"`
	Date string `json:"date,omitempty"`
	Comment string `json:"comment,omitempty"`
}
