/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2009Data struct {
	Id string `json:"id,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	// Three-letter ISO currency code. Must be upper-case
	Currency string `json:"currency,omitempty"`
	ExternalReference string `json:"external_reference,omitempty"`
	Status string `json:"status,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Customer *Customer `json:"customer,omitempty"`
	Receipts []InlineResponse2009Receipts `json:"receipts,omitempty"`
}
