/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Cost struct {
	Amount int32 `json:"amount,omitempty"`
	Currency string `json:"currency,omitempty"`
}
