/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type InlineResponse2004 struct {
	Data []Paths1paymentgetresponses200contentapplication1jsonschemapropertiesdataitems `json:"data,omitempty"`
	HasMore bool `json:"has_more,omitempty"`
	LastKey string `json:"last_key,omitempty"`
}
