/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	Limits []Limit `json:"limits,omitempty"`
	Features []Feature `json:"features,omitempty"`
	UserCount int32 `json:"user_count,omitempty"`
}
