/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Event struct {
	EventId string `json:"event_id"`
	Subscription string `json:"subscription"`
	Properties *interface{} `json:"properties,omitempty"`
	Value float32 `json:"value"`
	Code string `json:"code"`
}
