/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20012 struct {
	Paid bool `json:"paid,omitempty"`
	FailureReason string `json:"failure_reason,omitempty"`
}
