/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionStartBody struct {
	// The ID for the subscription plan to be used (Can also be the code name)
	SubscriptionPlan string `json:"subscription_plan"`
	// The Id for the customer's payment details to be used
	PaymentDetails string `json:"payment_details,omitempty"`
	// A stripe card token that's been created using Stripe's js sdk. It'll create the payment details for the customer.
	CardToken string `json:"card_token,omitempty"`
	// The ID for the price to be used
	Price string `json:"price,omitempty"`
	// The schedule of the plan that is to be started. Only used if price isn't given. Requires currency as well.
	Schedule string `json:"schedule,omitempty"`
	// The currency of the plan that is to be started. Only used if price isn't given. Requires schedule as well.
	Currency string `json:"currency,omitempty"`
	SeatNumbrers int32 `json:"seat_numbrers,omitempty"`
	DenyTrial bool `json:"deny_trial,omitempty"`
}
