/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type IssueRefundPayment struct {
	Amount int32 `json:"amount"`
	// Three-letter ISO currency code. Must be upper-case
	Currency string `json:"currency,omitempty"`
	Reason string `json:"reason,omitempty"`
}
