/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Metric struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Code string `json:"code,omitempty"`
	AggregationMethod string `json:"aggregation_method,omitempty"`
	AggregationProperty string `json:"aggregation_property,omitempty"`
	Filters []MetricFilter `json:"filters,omitempty"`
}
