/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse201Lines struct {
	SubscriptionPlan *SubscriptionPlan `json:"subscription_plan,omitempty"`
	Price *Price `json:"price,omitempty"`
	Description string `json:"description,omitempty"`
	Currency string `json:"currency,omitempty"`
	SeatNumber int32 `json:"seat_number,omitempty"`
	SubTotal int32 `json:"sub_total,omitempty"`
	TaxTotal int32 `json:"tax_total,omitempty"`
	TaxRate float64 `json:"tax_rate,omitempty"`
}
