/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type SubscriptionTrialBody struct {
	// The ID for the subscription plan to be used (Can also be the code name)
	SubscriptionPlan string `json:"subscription_plan"`
	// A stripe card token that's been created using Stripe's js sdk. It'll create the payment details for the customer.
	CardToken string `json:"card_token,omitempty"`
	SeatNumbrers int32 `json:"seat_numbrers,omitempty"`
	TrialLengthDays int32 `json:"trial_length_days,omitempty"`
}
