/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type MetricCost struct {
	// The name of the metric that the cost is for
	Name string `json:"name,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	Currency string `json:"currency,omitempty"`
	Usage float32 `json:"usage,omitempty"`
}
