/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.1.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package billabear

type Address struct {
	CompanyName string `json:"company_name,omitempty"`
	StreetLineOne string `json:"street_line_one,omitempty"`
	StreetLineTwo string `json:"street_line_two,omitempty"`
	City string `json:"city,omitempty"`
	Region string `json:"region,omitempty"`
	Country string `json:"country"`
	Postcode string `json:"postcode,omitempty"`
}
