/*
 * BillaBear
 *
 * The REST API provided by BillaBear
 *
 * API version: 1.0.0
 * Contact: support@billabear.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UsageLimit struct {
	Id string `json:"id,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	Action string `json:"action,omitempty"`
}
